name = "ginder-workers"
compatibility_date = "2024-08-07"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "ginder-repos"

 [ai]
 binding = "AI"

[[queues.producers]]
binding = "QUEUE"
queue = "ginder-repo-processing-queue"

[[kv_namespaces]]
binding = "CACHE"
id = "d1e788ede92a475697ff52a592512a1d"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
